### ISSUE TITLE
Use TSV instead of TXT so that GitHub displays a pretty, searchable table

### ISSUE THREAD

**Issue by sk22** [Metalab/KaraokeParty#1]
I think it'd be nice to replace the [songliste.txt](https://github.com/Metalab/KaraokeParty/blob/master/songliste.txt) with TSV file, like this:

https://gist.github.com/sk22/9e951aa10234fc9c8b0a2eeac4fd41f1

It'd be nice because GitHub displays well-formed CSV and TSV files as a table and adds a handy search bar!
Also, the existing songliste.txt is already almost a valid TSV, except:

* in line 100, there's a double-quote, which GitHub doesn't like – but it's just a typo anyway: `Don"t play that song`
* the comment on the first line needs to go
* the empty second line needs to go too
* add `Title	Artist` as the first line (or actually, to keep compatibility with the existing code, `# Title	Artist` would work too!) so GitHub shows a correct header

**Comment by anlumo** [comment]
I don't think that this list is maintained any more. This is now autogenerated based on the original database.

**Comment by sk22** [comment]
(i just saw that github cuts off the pretty table at 666 lines anyway)

**Comment by sk22** [comment]
@anlumo do you know if there's a publicly available link to the song list? because, like, songliste.txt is what https://metalab.at/wiki/KaraokeParty links to

**Comment by anlumo** [comment]
I don't think that there is any, @MacLemon only has them locally.

**Comment by MacLemon** [comment]
This thing hasn't been in use or maintained for almost a decade.
This repo should be archived, or even removed.
